### ISSUE TITLE
Humbug cancelling event in dev env, but not on main server

### ISSUE THREAD

**Issue by gipsy-king** [Civcraft/Burricos#4]
@rourke750 @ttk2 
Following [this part of the code](https://github.com/Civcraft/Humbug/blob/master/src/main/java/com/untamedears/humbug/Humbug.java#L1657) of Humbug, pressing E to open a donkey's inventory should always get cancelled. This works as expected on my dev env server where I have [Humbug-1.5.17.jar](http://civcraft.org:8080/job/Humbug-master/) and *either* latest 1.4 *or* 1.2  Burricos build.

Now, on the main server, I assume that there is latest Humbug and Burricos 1.2 as [stated here](http://www.reddit.com/r/Civcraft/comments/2qmcta/changelog_for_2014dec28/cn8ocw3?context=3). The event *does not get cancelled* - you can currently open a donkey's inv while riding it. Why?

Am I perhaps missing something? Is perhaps `prevent_vehicle_inventory_open` set to false on the main server config, if there is any config?

**Comment by rourke750** [comment]
On Civcraft https://github.com/Civcraft/Humbug/blob/master/src/main/java/com/untamedears/humbug/Humbug.java#L1639 might be set to false.

**Comment by gipsy-king** [comment]
`prevent_opening_container_carts` or `prevent_vehicle_inventory_open`?

`prevent_vehicle_inventory_open` would only affect generally opening minecart-chests, and should not interfere with opening horse inventories while riding them. `prevent_vehicle_inventory_open` would currently do block that.

**Comment by rourke750** [comment]
https://github.com/Civcraft/Humbug/blob/master/src/main/java/com/untamedears/humbug/Humbug.java#L1654

You can only open inventories if you are opening youre own.  If the config option is set to false you can open all inventory types.

**Comment by gipsy-king** [comment]
Yeah that's `prevent_vehicle_inventory_open`, that might be it.

Ok then, since I tested locally with latest humbug, Burricos-1.4 should be good to go @ttk2

**Comment by ttk2** [comment]
That's the one on the build server?

**Comment by gipsy-king** [comment]
yeah, 1.4, I just bumped the version with today's commit

**Comment by ttk2** [comment]
on civtest
