### ISSUE TITLE
Create "1.8" branch for PR

### ISSUE THREAD

**Issue by gipsy-king** [Civcraft/Burricos#6]
@rourke750 
To allow me to PR from https://github.com/gipsy-king/Burricos/tree/1.8

**Comment by rourke750** [comment]
https://github.com/Civcraft/Burricos/tree/1.8.3

Can you update it to the spigot version of 1.8.3 as well as thats the version we will most likely be jumping to.

**Comment by gipsy-king** [comment]
sure
