### ISSUE TITLE
Using burrico on donkey consumes all burricos in inventory

### ISSUE THREAD

**Issue by drjawa** [Civcraft/Burricos#8]
When you use one on a donkey, it consumes all of them in your inventory.

**Comment by rourke750** [comment]
@gipsy-king Did you see this?

**Comment by gipsy-king** [comment]
Yes, I will try to have this tomorrow. Do you have any idea what could be wrong with the code around [here](https://github.com/Civcraft/Burricos/blob/master/src/com/gipsyking/Burricos/Burricos.java#L205)?

**Comment by rourke750** [comment]
Yes .remove removes all items in the inventory that match that itemstack.  Do something similar to this https://github.com/Civcraft/Citadel/blob/master/src/vg/civcraft/mc/citadel/Utility.java#L117

**Comment by gipsy-king** [comment]
Oh shit, thanks!
